package com.example.dllo.baiduyinyue.mode.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "COLLECTION_BEAN".
 */
public class CollectionBean {

    private Long id;
    private String userName;
    private String userPassword;
    private String songName;
    private String author;
    private String songUrl;
    private byte[] pic;
    private String picUrl;
    private String other;
    private String others;

    public CollectionBean() {
    }

    public CollectionBean(Long id) {
        this.id = id;
    }

    public CollectionBean(Long id, String userName, String userPassword, String songName, String author, String songUrl, byte[] pic, String picUrl, String other, String others) {
        this.id = id;
        this.userName = userName;
        this.userPassword = userPassword;
        this.songName = songName;
        this.author = author;
        this.songUrl = songUrl;
        this.pic = pic;
        this.picUrl = picUrl;
        this.other = other;
        this.others = others;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserPassword() {
        return userPassword;
    }

    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    public String getSongName() {
        return songName;
    }

    public void setSongName(String songName) {
        this.songName = songName;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getSongUrl() {
        return songUrl;
    }

    public void setSongUrl(String songUrl) {
        this.songUrl = songUrl;
    }

    public byte[] getPic() {
        return pic;
    }

    public void setPic(byte[] pic) {
        this.pic = pic;
    }

    public String getPicUrl() {
        return picUrl;
    }

    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    public String getOther() {
        return other;
    }

    public void setOther(String other) {
        this.other = other;
    }

    public String getOthers() {
        return others;
    }

    public void setOthers(String others) {
        this.others = others;
    }

}
