package com.example.dllo.baiduyinyue.mode.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.dllo.baiduyinyue.mode.db.CollectionBean;

import com.example.dllo.baiduyinyue.mode.db.CollectionBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig collectionBeanDaoConfig;

    private final CollectionBeanDao collectionBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        collectionBeanDaoConfig = daoConfigMap.get(CollectionBeanDao.class).clone();
        collectionBeanDaoConfig.initIdentityScope(type);

        collectionBeanDao = new CollectionBeanDao(collectionBeanDaoConfig, this);

        registerDao(CollectionBean.class, collectionBeanDao);
    }
    
    public void clear() {
        collectionBeanDaoConfig.getIdentityScope().clear();
    }

    public CollectionBeanDao getCollectionBeanDao() {
        return collectionBeanDao;
    }

}
